add http interface
PolyhedraZK/Expander-rs pull request #21
Opened 2024-06-20 01:10 UTC by sixbigsquare

2024-06-20 23:29 UTC, niconiconi requested changes

2024-06-20 23:29 UTC, niconiconi commented on Cargo.toml
> +halo2curves = { git = "https://github.com/zhenfeizhang/halo2curves", default-features = false, features = [
dependency里面不能有个人的repo

2024-06-21 00:14 UTC, zhenfeizhang approved these changes
LGTM

2024-06-23 08:18 UTC, niconiconi approved these changes

2024-06-23 08:19 UTC, niconiconi approved these changes

2024-06-23 08:29 UTC, merged